CREATE TABLE IF NOT EXISTS "QUEUES" (
	"id"	INTEGER NOT NULL,
	"title"	TEXT NOT NULL,
	"src"	TEXT NOT NULL,
	"duration"	TEXT NOT NULL,
	"guid"	TEXT NOT NULL,
	"iat"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);

CREATE TABLE IF NOT EXISTS "HISTORY" (
	"id"	INTEGER NOT NULL,
	"title"	TEXT NOT NULL,
	"src"	TEXT NOT NULL,
	"duration"	TEXT NOT NULL,
	"guid"	TEXT NOT NULL,
	"iat"	INTEGER NOT NULL,
	PRIMARY KEY("id" AUTOINCREMENT)
);